### ISSUE TITLE
Nested BackHandler

### ISSUE THREAD

**Issue by zakrodionov** [adrielcafe/voyager#10]
In theory, the order of nested onBack functions should be from innermost up the chain. But in the current behavior, the opposite is true.

To repeat the steps, go to the nested navigation example, open 1 screen in each navigator and press the system back button 3 times.

**Comment by adrielcafe** [comment]
Fixed in [1.0.0-beta10](https://github.com/adrielcafe/voyager/releases/tag/1.0.0-beta10). Thanks again!

**Comment by zakrodionov** [comment]
@adrielcafe Thank you, your library is awesome!
