### ISSUE TITLE
Unable to compile ios app  using with compose multiplatform.

### ISSUE THREAD

**Issue by Kashif-E** [adrielcafe/voyager#121]
I am using the voyager in common main, the android build works fine but when compiling the Ios app it fails with the following error
```
> Task :common:linkPodDebugFrameworkIosSimulatorArm64 FAILED
e: There is still an unbound symbol after generation of IR module <common>:
Unbound public symbol IrSimpleFunctionPublicSymbolImpl: cafe.adriel.voyager.core.screen/Screen.Content|-3823403984862487740[0]

This could happen if there are two libraries, where one library was compiled against the different version of the other library than the one currently used in the project. Please check that the project configuration is correct and has consistent versions of dependencies.
```
Voyager version:  1.0.0-rc04

this is the project I am working on and issue is reproducible on the main branch: 
https://github.com/Kashif-E/KMPMovies

**Comment by pablichjenkov** [comment]
Are all your Composables internal?

**Comment by Kashif-E** [comment]
What can that be? I am trying to hack a thing out of it so any hacky way can work for now

**Comment by pablichjenkov** [comment]
For that you will need a separate build just for iOS. You will need to compile and build the voyager library in your end. You will end up using something like **implementation("cafe.adriel.voyager:voyager-navigator:$1.0.0-rc04")** and **implementation("cafe.adriel.voyager:voyager-navigator:$1.0.0-rc04-ios")**
The hack consist, for the iOS build or iOS version only, you make the Content() function internal.
@Composable
internal abstract fun Content()

Then in your iOS library you can have your screens like this. Even if you don't see the `override` keyword in the Content function, at runtime the Content() function gets resolved for the call.

class SimpleIOSScreen() : Screen {

    @Composable
    internal fun Content() {
        Box(modifier = modifier.fillMaxSize().background(bgColor)) {            
    }

}

**Comment by Kashif-E** [comment]
I did a hack but seems like even though compose gets converted to uikit but if you add a view at run time it does not get drawn

**Comment by pablichjenkov** [comment]
Ah sorry to hear man. 
That worked for me but I noticed that in my case, my class is a bit different than Voyager. I don't use expect/actual, I have a Component class similar to Screen that sits in my commonMain source. Anyways that solution is really hacky, is basically trying to call an external function with the same signature as of an internal to see if the class instance picks it up. 
We gotta wait for then.

**Comment by 7va** [comment]
You only need to set your Screen class/object as internal

```
internal class HomeScreen() : Screen {
    @Composable
    override fun Content() {
       ItemsList()
    }
}
```
