### ISSUE TITLE
Question about deep links

### ISSUE THREAD

**Issue by whitescent** [adrielcafe/voyager#135]
Does Voyager support deep links like Navigation Compose? 

![image](https://user-images.githubusercontent.com/31311826/234632780-5b1cf80b-e1ec-4d78-86b9-965eee42d2b6.png)

I couldn't find any documentation about it.

**Comment by alexzaitsev** [comment]
There is [a piece of documentation](https://voyager.adriel.cafe/deep-links) but it's not descriptive, unfortunately. Perhaps the author will add a better description, it would be great.

**Comment by DevSrSouza** [comment]
No, Voyager just provide a simple example of you can manage your self Deeplinks.

We plan, in the future, to provide a better deeplink support out of the box, but currently we don't have time for it.

**Comment by Raynafs** [comment]
@DevSrSouza is there a sample implementation? 
The documentation is difficult to understand

**Comment by yangwuan55** [comment]
> @DevSrSouza is there a sample implementation? The documentation is difficult to understand

+1
