### ISSUE TITLE
Cannot use stateIn operator inside ScreenModel

### ISSUE THREAD

**Issue by isshindev** [adrielcafe/voyager#14]
Using `stateIn` operator inside `ScreenModel` **using built-in coroutineScope** cause a crash with `java.lang.IllegalStateException:  ScreenModel not found`. However, this exception doesn't happen if self-created Coroutine scope is used.
Example code,
```
class TestScreen : Screen {
    @Composable
    override fun Content() {
        val sm = rememberScreenModel { TestScreenModel() }
        val msg by sm.msg.collectAsState()
        Text(msg)
    }
}

class TestScreenModel : ScreenModel {
    val msg = msgFlow.stateIn(coroutineScope, SharingStarted.Lazily, "")
}

val msgFlow = listOf("Hello", "world!").asFlow()
```

**Comment by adrielcafe** [comment]
Fixed in [1.0.0-beta12](https://github.com/adrielcafe/voyager/releases/tag/1.0.0-beta12). Thanks for reporting!
