### ISSUE TITLE
The issue with saving the list state upon closing the detail screen in nested navigation with tabs.

### ISSUE THREAD

**Issue by marazmone** [adrielcafe/voyager#143]
**Description:** 

I have encountered an issue with nested navigation using tabs. Although the list appears okay when I switch tabs, the problem arises when I navigate back from a screen within the parent navigation. At this point, the list's state resets, causing unexpected behavior.

**Video:**
https://github.com/marazmone/ios-compose-showcase/assets/7988862/acf15265-f4af-450c-853c-6dc56233f63d

**Code example:**
https://github.com/marazmone/ios-compose-showcase

**Comment by afTrolle** [comment]
I ran into the same issue, Viewmodels are cleared when scoped to the Nested-Navigator. 
I had Nested Navigators, So I did a work around using the parent screen to scope my viewmodels then It works. Just note that this could lead to viewmodels being shared between tabs.

```Kotlin
val parentScreen = LocalNavigator.current?.parent?.lastItem!!
val viewModel = parentScreen.getScreenModel<HomeScreenModel>()
```

**Comment by Rhacoal** [comment]
I've also run into the same issue. With some debugging into the source, I figured out that the nested `TabNavigator` gets disposed when switching to another screen (since it does not exist on the other screen) and states are lost.

Adding `disposeBehavior = NavigatorDisposeBehavior(disposeNestedNavigators = false)` to the arguments of the outer Navigator solved my issue. The parent navigator now looks like this:

```kotlin
Navigator(MainScreen, disposeBehavior = NavigatorDisposeBehavior(disposeNestedNavigators = false))
```

**Comment by DevSrSouza** [comment]
Hopefully the @Rhacoal solution fix for you folks. If did not, feel free to re open the issue

**Comment by marazmone** [comment]
> I've also run into the same issue. With some debugging into the source, I figured out that the nested `TabNavigator` gets disposed of when switching to another screen (since it does not exist on the other screen) and states are lost.
> 
> Adding `disposeBehavior = NavigatorDisposeBehavior(disposeNestedNavigators = false)` to the arguments of the outer Navigator solved my issue. The parent navigator now looks like this:
> 
> ```kotlin
> Navigator(MainScreen, disposeBehavior = NavigatorDisposeBehavior(disposeNestedNavigators = false))
> ```

Thank you! It has really resolved my problems!
