### ISSUE TITLE
Error: Module with the Main dispatcher is missing on Desktop ScreenModel

### ISSUE THREAD

**Issue by Aviator737** [adrielcafe/voyager#147]
<img width="422" alt="image" src="https://github.com/adrielcafe/voyager/assets/6958547/0c83a7a5-e345-4f79-b3e6-192fd9f78ebb">

Using coroutineScope on desktop leads me to this error:

Module with the Main dispatcher is missing. Add dependency providing the Main dispatcher, e.g. 'kotlinx-coroutines-android' and ensure it has the same version as 'kotlinx-coroutines-core'

**Comment by akardas16** [comment]
in some cases I still get this error although I have added adding swing dependency. Basicly you can just use IO dispatcher without any issue
```
 fun hello(string:String){
        coroutineScope.launch(Dispatchers.IO) {
            //mutableState.value = State.Loading
            _userList.value = string
        }
    }
```
