### ISSUE TITLE
Navigation in activity onNewIntent

### ISSUE THREAD

**Issue by ghostmane0404** [adrielcafe/voyager#149]
Let's consider a scenario where we have an activity with two screens: ListScreen and DetailScreen. The activity is defined as follows:
class SomeActivity : AppCompatActivity() {

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
      
        setContent {
            Navigator(
                remember {
                    ListScreen(),
                    DetailScreen(someId)
                },
            )
        }
    }

    override fun onNewIntent(intent: Intent) {
        super.onNewIntent(intent)
    }
}
When a user opens a deep link, the onNewIntent method is triggered, and we want to redirect them to the DetailScreen. How can i do that, is navigator accesible in activity?

**Comment by ghostmane0404** [comment]
@adrielcafe id appreciate any help

**Comment by Syer10** [comment]
```kotlin
override fun onCreate(savedInstanceState: Bundle?) {
    super.onCreate(savedInstanceState)
  
    setContent {
        val context = LocalContext.current
        Navigator(
            remember {
                ListScreen(),
                DetailScreen(someId)
            },
        ) { navigator ->
            CurrentScreen()
            HandleOnNewIntent(context, navigator)
        }
    }
}

@Composable
fun HandleOnNewIntent(context: Context, navigator: Navigator) {
    LaunchedEffect(Unit) {
        callbackFlow<Intent> {
            val componentActivity = context as ComponentActivity
            val consumer = Consumer<Intent> { trySend(it) }
            componentActivity.addOnNewIntentListener(consumer)
            awaitClose { componentActivity.removeOnNewIntentListener(consumer) }
        }.collectLatest { handleIntentAction(it, navigator) }
    }
}

fun handleIntentAction(intent: Intent, navigator: Navigator) {
    // handle intent
}
```

**Comment by burnoo** [comment]
In addition to @Syer10 response (great solution btw): if you want to support deeplinks clicks when the app is not opened, you can modify `HandleOnNewIntent` as follows:

```kotlin
@Composable
fun HandleIntent(context: Context, navigator: Navigator) {
    LaunchedEffect(Unit) {
        callbackFlow<Intent> {
            val componentActivity = context as ComponentActivity
            val currentIntent = componentActivity.intent
            if (currentIntent?.data != null) {
                trySend(currentIntent)
            }
            val consumer = Consumer<Intent> { trySend(it) }
            componentActivity.addOnNewIntentListener(consumer)
            awaitClose { componentActivity.removeOnNewIntentListener(consumer) }
        }.collectLatest { handleIntentAction(it, navigator) }
    }
}
```

**Comment by DevSrSouza** [comment]
Close this as resolved, we futher can provide this issue in a Q&A of Voyager to help guide future adopters of the library.

Thanks folks

**Comment by NavorJames** [comment]
I would like to ask for more examples regarding deeplinks working together with nested navigation and tab navigation
