### ISSUE TITLE
Documentation enhancement: "Coroutines integration" in Desktop

### ISSUE THREAD

**Issue by mateuy-dev** [adrielcafe/voyager#150]
When using "Coroutines integration" in Desktop apps I've been required to add the swing coroutines dependency (to enable Main dispatcher):

```
runtimeOnly("org.jetbrains.kotlinx:kotlinx-coroutines-swing:1.6.4")
```

If it is not added the app may crash (in some lucky cases like a coroutineScope.lauch) or may silently not work if you are using a stateIn with the ViewModel scope like the following

```
myFlow.stateIn(scope = coroutineScope) // this silently fails if swing coroutines are not added
```

**Comment by Syer10** [comment]
This doesn't have anything to do with Voyager. Compose for Deaktop itself needs the Swing dispatcher or else anything you try to run on thr main thread will crash your application.

**Comment by mateuy-dev** [comment]
You can create Compose Desktop apps without using the Main Dispatcher. For example Compose Desktop templates do not include it.
I think it would be nice to have it as a warning on the website docs.

**Comment by YuuHaruna** [comment]
> When using "Coroutines integration" in Desktop apps I've been required to add the swing coroutines dependency (to enable Main dispatcher):
> 
> ```
> runtimeOnly("org.jetbrains.kotlinx:kotlinx-coroutines-swing:1.6.4")
> ```
> 
> If it is not added the app may crash (in some lucky cases like a coroutineScope.lauch) or may silently not work if you are using a stateIn with the ViewModel scope like the following
> 
> ```
> myFlow.stateIn(scope = coroutineScope) // this silently fails if swing coroutines are not added
> ```

So I just need to add this to desktopApp module, or anywhere else. And after adding that, do I have to do anything else. I've just added this to build gradle of desktopApp and it still crash when I use voyager coroutineScope.

**Comment by akardas16** [comment]
> So I just need to add this to desktopApp module, or anywhere else. And after adding that, do I have to do anything else. I've just added this to build gradle of desktopApp and it still crash when I use voyager coroutineScope.

https://github.com/adrielcafe/voyager/issues/147#issuecomment-1717612820

**Comment by DevSrSouza** [comment]
Done: https://voyager.adriel.cafe/screenmodel/coroutines-integration#desktop-note
