### ISSUE TITLE
[Question]: Kotlin-Inject Support

### ISSUE THREAD

**Issue by c0de-wizard** [adrielcafe/voyager#153]
Hey, I'm in the process of migrating my kmm project to Voyager. Does it have support for [Kotlin-inject](https://github.com/evant/kotlin-inject)?

**Comment by Syer10** [comment]
Kotlin-Inject is a very flexible framework, there is no one way to do something. I use it in my hobby project with Voyager so feel free to look at how I integrated them.

https://github.com/Suwayomi/Tachidesk-JUI/blob/master/presentation/src/commonMain/kotlin/ca/gosyer/jui/ui/ViewModelComponent.kt#L87

https://github.com/Suwayomi/Tachidesk-JUI/blob/master/presentation/src/commonMain/kotlin/ca/gosyer/jui/ui/settings/SettingsAdvancedScreen.kt#L65

https://github.com/Suwayomi/Tachidesk-JUI/blob/master/presentation/src/commonMain/kotlin/ca/gosyer/jui/ui/base/UiComponent.kt#L49

**Comment by c0de-wizard** [comment]
Sweet. Thank @Syer10 I will take a look.
