### ISSUE TITLE
Missing getScreenModel with voyager-koin

### ISSUE THREAD

**Issue by har-nick** [adrielcafe/voyager#163]
I have a Kotlin Multiplatform project with Voyager dependencies in commonMain like so:
```
implementation("cafe.adriel.voyager:voyager-bottom-sheet-navigator:" + extra["voyager.version"] as String)
implementation("cafe.adriel.voyager:voyager-koin:" + extra["voyager.version"] as String)
```

Screen Model is listed in a Koin module:
```
val commonModule = module {
    single<LibraryRepo> { LibraryRepoImpl(bandcampApi = get()) }
    factory { LibraryModel(libraryRepo = get()) }
}
```

Model:
```
class LibraryModel(private val libraryRepo: LibraryRepo) : StateScreenModel<LibraryState>(LibraryState()) {
}
```

Screen:
```
object LibraryScreen : Screen {
    @Composable
    override fun Content() {
        val libraryModel: LibraryModel = getScreenModel()
    }
}
```

However `getScreenModel()` is marked as an unresolved reference.

**Comment by Syer10** [comment]
The Koin module currently only supports android due to previous versions of Koin not supporting Compose for Desktop, there is a PR to include other platforms now that koin supports it here #159.

**Comment by har-nick** [comment]
Thank you for the prompt response. I'll mark this as closed.
