### ISSUE TITLE
Support for kotlin/wasm

### ISSUE THREAD

**Issue by sunildhiman90** [adrielcafe/voyager#165]
Hi , 

i was trying to implement it in compose multiplatform project with kotlin/wasm support, But it does not work.
I got this error:
```
Could not determine the dependencies of task ':shared:wasmPackageJson'.
> Could not resolve all dependencies for configuration ':shared:wasmNpm'.
   > Could not resolve cafe.adriel.voyager:voyager-navigator:1.0.0-rc06.
     Required by:
         project :shared
      > No matching variant of cafe.adriel.voyager:voyager-navigator:1.0.0-rc06 was found. The consumer was configured to find a library for use during 'kotlin-runtime', preferably optimized for non-jvm, as well as attribute 'org.jetbrains.kotlin.platform.type' with value 'wasm' but:
          - Variant 'debugApiElements-published' capability cafe.adriel.voyager:voyager-navigator:1.0.0-rc06 declares a library:
              - Incompatible because this component declares a component for use during compile-time, as well as attribute 'org.jetbrains.kotlin.platform.type' with value 'androidJvm' and the consumer needed a component for use during 'kotlin-runtime', as well as attribute 'org.jetbrains.kotlin.platform.type' with value 'wasm'

```

Are we planing to add support for koltin/wasm any recently?

Thanks

**Comment by programadorthi** [comment]
There is a little sample using WASM [here](https://github.com/adrielcafe/voyager/blob/main/samples/multiplatform/src/jsMain/kotlin/main.js.kt). But the repo is not updated with latest Kotlin WASM release.

**Comment by Irineu333** [comment]
@sunildhiman90 I had the same error, were you able to use it with Kotlin Wasm?

**Comment by sunildhiman90** [comment]
Hi @Irineu333, i postponed work on it. So i didnt tried it again actually. If i will try it, i will let u know.

**Comment by Irineu333** [comment]
> There is a little sample using WASM [here](https://github.com/adrielcafe/voyager/blob/main/samples/multiplatform/src/jsMain/kotlin/main.js.kt). But the repo is not updated with latest Kotlin WASM release.

Yes, in my case I wanted the target to be Kotlin/Wasm. But for now, I'll continue with Kotlin/JS, as Kotlin/Wasm is still very unstable.

**Comment by joreilly** [comment]
Hi, curious of any plans still to support Wasm target now that it's reached alpha.
