### ISSUE TITLE
new screen back screen,screenModel  rebuilt?

### ISSUE THREAD

**Issue by PostLiu** [adrielcafe/voyager#172]
I created a HomeScreenModel in HomeScreen, using rememberScreenModel call, when I jump to a new Screen and then return to HomeScreen, HomeScreenModel is recreated, how do I save the state of HomeScreenModel
`
object Home : Screen {

        override val key: ScreenKey
            get() = uniqueScreenKey

        @Composable
        override fun Content() {
            val homeScreenModel = rememberScreenModel<HomeScreenModel>()
            HomePage(homeScreenModel = homeScreenModel)
        }
    }
`

**Comment by Syer10** [comment]
You need to save the uniqueScreenKey, so you cannot use `get()`
```kotlin
object Home : Screen {

    override val key: ScreenKey = uniqueScreenKey

    @Composable
    override fun Content() {
        val homeScreenModel = rememberScreenModel<HomeScreenModel>()
        HomePage(homeScreenModel = homeScreenModel)
    }
}
```

**Comment by PostLiu** [comment]
> 

ok,it's work
