### ISSUE TITLE
How to avoid "transition was used multiple times" error?

### ISSUE THREAD

**Issue by thawri1** [adrielcafe/voyager#175]
refer to #23, I must use `uniqueScreenKey` for the screen key if I want to use Transition between screens.
but what to do if I want to use a specific key for the screen?
by using `uniqueScreenKey` for the screen key, if I go back to the screen, a new screen model is created and this is not the behavior I want.
if set "standard" for `launchMode` in the manifest there is no problem. but I need to set it as "singleTop"
also, no problem if set android:noHistory="true".

**Comment by Syer10** [comment]
Are you not storing the value of uniqueScreenKey? You might be doing the same thing as https://github.com/adrielcafe/voyager/issues/172, so I would suggest checking that issue out. The main thing to look at, is don't use `get() =`

**Comment by thawri1** [comment]
> Are you not storing the value of uniqueScreenKey? You might be doing the same thing as #172, so I would suggest checking that issue out. The main thing to look at, is don't use `get() =`

thank you.
I struggling with this problem for many hours!
