### ISSUE TITLE
ScreenModel is getting disposed on a deep link trigger

### ISSUE THREAD

**Issue by mslalith** [adrielcafe/voyager#177]
Whenever a deep link is consumed by the app, the screen model is getting disposed and recreated again

```kotlin
object DeepLinkRegistry {

    internal val buffer = MutableSharedFlow<String>(replay = 1)

    fun handle(deepLink: String) {
        buffer.tryEmit(value = deepLink)
    }
}

@OptIn(ExperimentalCoroutinesApi::class)
@Composable
fun Screen.DeepLinkHandler(block: (String) -> Unit) {
    LaunchedEffect(key1 = key) {
        with(DeepLinkRegistry.buffer) {
            collectLatest {
                block(it)
                resetReplayCache()
            }
        }
    }
}
```

I'm using like below in Screen
```kotlin
DeepLinkHandler { screenModel.handleDeepLink(deepLink = it) }
```

**Comment by mslalith** [comment]
Right, when remembering ScreenModel, it will be added to `ScreenModelStore.screenModels` with it's respective screen key. I did not explicitly give any key, so voyager takes qualified screen class name as key. Screen key stays the same but not it's associated ScreenModel.
Also I see `ScreenModelStore.remove` is getting called which will remove the screen and dispose it's dependencies. I feel that this is causing the issue

**Comment by Syer10** [comment]
What issue are you having? It seems like all the deep link stuff is your custom code, so I can't think of anything that could be a Voyager issue.

**Comment by DevSrSouza** [comment]
Closing because of no response, if you still have the issue and still think is related to Voyager, feel free to re-open and give us more examples that we can reproduce it.
