### ISSUE TITLE
Disable BottomSheet drag to dismiss

### ISSUE THREAD

**Issue by jordond** [adrielcafe/voyager#178]
Is it possible to stop a BottomSheetNavigator from dismissing when swiped down?

**Comment by Ulan-e** [comment]
I tried the gesture intercept and it didn't work.

**Comment by adrielcafe** [comment]
On [1.0.0-rc07](https://github.com/adrielcafe/voyager/releases/tag/1.0.0-rc07) you can disable gestures this way:
```kotlin
BottomSheetNavigator(
  sheetGesturesEnabled = false
)
```

**Comment by Ulan-e** [comment]
Thanks)
