### ISSUE TITLE
ScreenModel in first Screen isn't disposable

### ISSUE THREAD

**Issue by daniaviladomingo** [adrielcafe/voyager#187]
If you have only one Screen(Screen1) with ScreenModel associated, when you pulse back button ScreenModel isn't disposed.
But if you have a previous Screen(PreviousScreen) before Screen1 when you pulse back button from Screen1 and navigate to PreviousScreen then ScreenModel associated to Screen1 is disposed so.

In Screen1 (ScreenModel associated) => pop or back navigation => ScreenModel not disposed (Only one screen and first)
In PreviousScreen => navigate to Screen1 (ScreenModel associated) => pop or back navigation => ScreenModel is disposed (Two screen and second)

I think the problem is on the first screen with ScreenModel associated.

Thanks for this fantastic project

**Comment by programadorthi** [comment]
Hi @daniaviladomingo . Navigator needs at least a screen to work. If you have only one screen, after back press you need remove the Navigator from composition. So, having only one Screen with a ScreenModel associated, they will be disposed when the Navigator been out of the current Composition.
Try override onBackPressed to close your current composition owner or to replace Navigator by a new one or another composition that will trigger Screen and ScreenModel onDispose.
That was solved on #55

**Comment by programadorthi** [comment]
I did test in latest version and ScreenModel still been disposed using Single Screen and Multiple Screen.
So, I'm closing this issue
