### ISSUE TITLE
Key search:transition was used multiple times

### ISSUE THREAD

**Issue by savan-ixfi** [adrielcafe/voyager#197]
<img width="1294" alt="image" src="https://github.com/adrielcafe/voyager/assets/131661149/568e7ba6-a5ea-48ef-9294-493c76b29b93">

video
https://github.com/adrielcafe/voyager/assets/131661149/f92672ce-700b-40eb-aa75-554ef8008681

**Comment by faa0** [comment]
Have you found a solution?

**Comment by savan-ixfi** [comment]
right now i am used a temporary solution like below solution using screenNo

var screenNo: Int = 1

val LocalScreenContainer =
    compositionLocalOf<ScreenContainer> { error("screen container not found") }

fun screenContentOf(key: String? = null, content: @Composable () -> Unit): Screen {
    screenNo += 1
    return object : Screen {
        override val key: ScreenKey = (key ?: super.key) + screenNo.toString()

        @Composable
        override fun Content() {
            content.invoke()
        }
    }
}

**Comment by DevSrSouza** [comment]
@savan-ixfi Did you try to use a unique key in the your screen? This is a requirement if you are pushing the same screen twice.

Voyager has an extension called `uniqueScreenKey`, can you check it out if fix for your?
If you don't put this on all Screens, you can create your own screen type, for example:

```kotlin
abstract class MyBaseScreen : Screen {
    override val key: ScreenKey = uniqueScreenKey
}
```

**Comment by DevSrSouza** [comment]
Update here: this can also happen if we are pushing the same screen by accident, for example, by flooding a button that does a `push(ScreenX())`, it can happen to push the same screen twice and give you this error.

So, again, the final solution is the same as I shared above, using `uniqueScreenKey`

**Comment by DevSrSouza** [comment]
I will close this issue as solved, if this solution did not solve for you, please provide more examples and feel free reopen the issue.
