### ISSUE TITLE
Handling back press with a popup window

### ISSUE THREAD

**Issue by blonsky95** [adrielcafe/voyager#198]
Hi, I recently added Voyager into my project to handle navigations. I also needed handling back presses so I am giving it a go using this: https://voyager.adriel.cafe/back-press 

I find it useful to handle back presses that affect navigation at top level hierarchy. However what if I have a screen that opens an alert window (or popup) and I want back press to be one of:
A) Ignored
B) detected at composable level (like a BackHandler) so I can dismiss the dialog

Right now the back button is handled at top level so it doesnt care if a dialog is open, it will have the same behaviour as when there is no dialog.

Is there a different way to handle this? Or is there more documentation on back presses I am missing?

**Comment by Syer10** [comment]
Voyager just hooks into the Android BackHandler, so you can make your own `BackHandler { // my action }`, Backhandlers further down in the composable tree have priority.

**Comment by blonsky95** [comment]
Yeah so I understand what you would do is create an expect BackHandler and have android implement its own actual BackHandler, and ios to do nothing, yeah makes sense!
