### ISSUE TITLE
[Question] How to handle opening app permissions and changing of it state

### ISSUE THREAD

**Issue by aradomski** [adrielcafe/voyager#199]
I'm writing multiplatform app for android and iOS. When user doesn't allow for location permission on android after showing rationale I need to open system settings. User can there change decision about requested permission. Usually on android when we are getting back from settings onResume is triggered. But here I don't see this option.
I checked 
`   LifecycleEffect(onStarted = {
            println("on started")
        })`
        
but it wasn't triggered after getting back from settings.
        
How to achieve onResume like functionality?

**Comment by Deorigami** [comment]
// Common Code

```
enum class LifecycleState {
    ON_RESUME,
    ON_PAUSE,
    ON_START
}

expect object LifecycleHelper {
    val value : MutableStateFlow<LifecycleState>
}

@Composable fun rememberAppLifecycle() : State<LifecycleState>
```

// Android

```
actual object LifecycleHelper {
    actual val value : MutableStateFlow<LifecycleState> = MutableStateFlow(LifecycleState.ON_PAUSE)
}
```

// IOS

create file LifeCycleHelper.kt

```
fun onPause(){
    LifecycleHelper.value.value = LifecycleState.ON_PAUSE
}

fun onResume(){
    LifecycleHelper.value.value = LifecycleState.ON_RESUME
}

fun onStart(){
    LifecycleHelper.value.value = LifecycleState.ON_START
}

```
and in iosApp.swift

```
@main
struct iosApp: App {
    
    @Environment(\.scenePhase)
        var scenePhase: ScenePhase
    @UIApplicationDelegateAdaptor(AppDelegate.self) var appDelegate

    
    var body: some Scene {
        WindowGroup {
            ContentView()
                .onChange(of: scenePhase){ newPhase in
                    switch newPhase {
                    case .background: LifecycleHelperKt.onStart()
                    case .inactive: LifecycleHelperKt.onPause()
                    case .active: LifecycleHelperKt.onResume()
                    @unknown default: break
                    }
                }
                
        }
    }
}
```

// IN Common Composable you can do
```
val appLifeCycle by rememberAppLifecycle()
Napier.d(tag = "ANGGATAG", message = appLifeCycle.toString());
```

**Comment by DevSrSouza** [comment]
I think this is more a question about Compose itself and it life cycle and not about Voyager.

If there is any question specific about Voyager that I did understand from the issue, feel free to reopen
