### ISSUE TITLE
Wrap Navigator with AnimatedVisibility produce reset navigator to initial screen

### ISSUE THREAD

**Issue by Alexbeard** [adrielcafe/voyager#2]
Hi, many thanks for your library. I have tried it a bit and it's very powerful.

I have noticed when I wrap Navigator with AnimatedVisibility it is reset to the initial screen.

I created my own scaffold with slots, I need to use different navigators in each slot. In one slot in the scaffold root, I need to use AnimatedVisibility to produce hide/collapse animation, and in this slot I need to maintain some navigation. So after I create navigation in that AnimatedVisibility composable I have noticed that when it exit to the invisible state navigator also resets its state to the initial state.

Can you provide some ideas of how I can achieve some animation around box that contains navigator ?

**Comment by adrielcafe** [comment]
Can you try with `Crossfade` and see if works?

Currently I'm doing some experiments with animations (to provide some common transitions) and I also had issues with `AnimatedVisibility` and `AnimatedContent`, only the `Crossfade` worked.

I think that's because Voyager keeps only the current screen (and not a list of screens) in the composition. Since `Crossfade` switches one screen per another, it works as expected, but other kinds of animations not.

I'll keep experimenting, hope to have something working soon.

**Comment by Alexbeard** [comment]
I have tried `Crossfade` just now and it seems that it doesn't change anything it works the same as with `AnimatedVisibility` . Maybe I am doing it in some strange way but I need to modify the box where the navigation should happen, modify its size and visibility, since that I need to do it one step above that I am doing navigation, my animation is not wrapped in the `Navigator`.

**Comment by adrielcafe** [comment]
Can you provide a video and/or sample project so I can understand better the issue?

**Comment by Alexbeard** [comment]
Sure, I have been working on my pet [project](https://github.com/Alexbeard/FloatingPannelScaffold/tree/bug/navigation_sample).
I have made for you a branch called `bug/navigation_sample` and in the `master` you can see the working workaround.
There is some logic that I want to achieve, I don't wanna show the `sidePanel `if there is empty screen and the state of scaffold is not in the `listmode`, only when I am in the `listmode` I can see the `empty screen`.

Steps to reproduce bug: 
1. Click in the bottom sheet on the `ListMode` button.
2. Click in side panel on the `"Empty Side Panel"` text.
3. Then again press `ListMode` button it will produce the state when it is collapsed but `sidePanel` should stay, it's okey.
4. Then try to press `ExpandSide` button to collapse/expand it.

You will notice that in the `master` branch it opens/closes the side panel with the list. But in the branch with bug it reset state of the side panel screen to the initial so it is not open anymore.

**Comment by adrielcafe** [comment]
I believe I've found the issue. Your code was initializing the `Navigator` with `SidePanelEmptyScreen` as the initial screen:
```
Navigator(SidePanelScreens.SidePanelEmptyScreen) { sidePanelNavigator ->
```

But you are keeping the current screen in your own state, `sidePanelScreen` (which is set outside the `Navigator`). I changed the initial screen to:
```
Navigator(sidePanelScreen) { sidePanelNavigator ->
```

Can you confirm if this fixes?

**Comment by Alexbeard** [comment]
Thanks man you are right, everything work as expected. 

I have another few questions about library, where I can ask them?

**Comment by adrielcafe** [comment]
Great!

If the questions are related to Voyager, you can use the [discussions](https://github.com/adrielcafe/voyager/discussions) page. If are general questions send me an email: me at adriel.cafe
