### ISSUE TITLE
android.os.BadParcelableException

### ISSUE THREAD

**Issue by savan-ixfi** [adrielcafe/voyager#208]
crash code
<img width="762" alt="image" src="https://github.com/adrielcafe/voyager/assets/131661149/628d15a0-050e-452e-8946-ba3d809fe715">

crash
<img width="1285" alt="image" src="https://github.com/adrielcafe/voyager/assets/131661149/bd651fdc-f905-493b-9376-4a6bfe9951ca">
<img width="1005" alt="image" src="https://github.com/adrielcafe/voyager/assets/131661149/387b0aac-06b4-467d-a139-730cd05b8c0e">

**Comment by savan-ixfi** [comment]
> Thats a bad way to create a Screen, Screens are Serializable, and Lamba's cant be used in Serializable objects. I would say rewrite it using the normal way.

Could you please explain with example how to sortout?

**Comment by Syer10** [comment]
https://voyager.adriel.cafe/navigation
