### ISSUE TITLE
android.os.BadParcelableException

### ISSUE THREAD

**Issue by savan-ixfi** [adrielcafe/voyager#209]
getting below issue when app is going in background

<img width="1304" alt="image" src="https://github.com/adrielcafe/voyager/assets/131661149/066808bf-5357-4890-96b0-b8dcb01dee01">

example code:
<img width="561" alt="image" src="https://github.com/adrielcafe/voyager/assets/131661149/97225ec4-9414-409d-9068-3984c73ae6df">
<img width="613" alt="image" src="https://github.com/adrielcafe/voyager/assets/131661149/a466b45c-6271-4b2a-8b88-8f2d421e01de">

**Comment by Syer10** [comment]
You will need to expect/actual the Serializable interface in compose multiplatform, and just define a empty interface on non-jvm platforms.

**Comment by savan-ixfi** [comment]
but in my i used
kotlinx.serialization.Serializable

**Comment by savan-ixfi** [comment]
> You will need to [expect/actual](https://kotlinlang.org/docs/multiplatform-connect-to-apis.html) the Serializable interface in compose multiplatform, and just define a empty interface on non-jvm platforms.

but in my i used
kotlinx.serialization.Serializable

**Comment by Syer10** [comment]
Kotlin-x Serializable != Java Serializable, Voyager needs Java Serializable

**Comment by savan-ixfi** [comment]
> Kotlin-x Serializable != Java Serializable, Voyager needs Java Serializable

i understand so Kotlin-x Serializable is not supported by voyager right?

but i am using ktor with Kotlin-x Serializable so how to resolve this issue?

**Comment by Syer10** [comment]
I cannot help you anymore, I've tried to explain it a few times already.

**Comment by savan-ixfi** [comment]
<img width="829" alt="image" src="https://github.com/adrielcafe/voyager/assets/131661149/d40a0cb2-c401-4e34-9fab-ed7b2b22e88b">


> I cannot help you anymore, I've tried to explain it a few times already.

Java Serializable wrapper also not working
<img width="829" alt="image" src="https://github.com/adrielcafe/voyager/assets/131661149/9920fbac-4771-418c-8901-e7ad12ae9952">
<img width="707" alt="image" src="https://github.com/adrielcafe/voyager/assets/131661149/cab5e1f3-e6b1-4140-8151-0a5d1239b8c6">

**Comment by savan-ixfi** [comment]
> I cannot help you anymore, I've tried to explain it a few times already.

Java Serializable wrapper also not working
<img width="604" alt="image" src="https://github.com/adrielcafe/voyager/assets/131661149/96504a87-d676-4d82-8c26-f5f9e78ea2e8">
<img width="616" alt="image" src="https://github.com/adrielcafe/voyager/assets/131661149/4fcc9df6-d309-4cec-b9a1-d0e2c8373400">

**Comment by savan-ixfi** [comment]
Thanks resolve it
