### ISSUE TITLE
How to handle back navigation in tabNavigator

### ISSUE THREAD

**Issue by savan-ixfi** [adrielcafe/voyager#214]
When i back from any other tab it's move to primary tab and then back from application

Example video of what is my actual requirement

https://github.com/adrielcafe/voyager/assets/131661149/4d54a8df-b9ab-475b-acca-f78380b45db7

**Comment by Syer10** [comment]
Add a BackHandler that activates when the Navigator only has 1 screen
```
BackHandler(navigator.items.size == 1) {
    // navigate to home tab
}
```

**Comment by savan-ixfi** [comment]
<img width="620" alt="image" src="https://github.com/adrielcafe/voyager/assets/131661149/6b16aee1-ed6c-4e43-8aff-1c4ef9e92008">


> Add a BackHandler that activates when the Navigator only has 1 screen
> 
> ```
> BackHandler(navigator.items.size == 1) {
>     // navigate to home tab
> }
> ```

Unresolved reference: BackHandler
<img width="620" alt="image" src="https://github.com/adrielcafe/voyager/assets/131661149/1920d2c8-c18d-4a80-ba58-f838e460a7fc">

**Comment by Syer10** [comment]
If you are using a common sourceset you might need to expect/actual the `BackHandler` from Androidx Activity Compose

**Comment by savan-ixfi** [comment]
> If you are using a common sourceset you might need to expect/actual the `BackHandler` from Androidx Activity Compose

how to move from last tab to first tab on button click of last tab?
