### ISSUE TITLE
Kodein For KMP

### ISSUE THREAD

**Issue by pradyotprksh** [adrielcafe/voyager#215]
I am using the rememberScreenModel function with the Kodein in a Kotlin Multiplatform Library

**DI class**
```
object KodeinDI {
    private val appModule = DI.Module(name = "app") {
        bindProvider { SplashViewModel(instance()) }
    }

    /** Some other modules **/

    val di = DI { importAll(appModule, repository, service, api) }
}
```

**Model class**
```
class SplashViewModel(
    override val di: DI,
): StateScreenModel<SplashViewModel.State>(State.Init), DIAware {
    private val repository: Repository by instance()

    sealed interface State {
        data object Init : State
        data object Loading : State
    }

    /** Business Login **/
}
```

**Scree class**
```
class SplashView: Screen {
    @Composable
    override fun Content() {
        val splashViewModel = rememberScreenModel<SplashViewModel>()

        /** UI Logic **/
    }
}
```

But with the above code I am getting the below error
`java.lang.IllegalStateException: Trying to find closest DI, but no DI container was found at all. Your Application should be DIAware.`

Not able to get on how to fix it.

As per the sample from https://voyager.adriel.cafe/screenmodel/kodein-integration, the Kodein is being lazyly created in the first Activity screen. But with KMP how we can achieve it and make the `rememberScreenModel` works.

Could anyone help me to understand the steps on making the above requirement work?

Thanks in advance.

**Comment by DevSrSouza** [comment]
When running Kodein in a multiplatform project with Compose is require to define the DI Graph at the Compose application. Differently from Koin that has a Singleton DI Graph, Kodein always depend on some type of context.

If I recall correctly it will require you to call withDi(yourGlobalKodeinDiGraph){ YourApplicationComposable() }

__commented in phone__

**Comment by DevSrSouza** [comment]
I will close here. Feel free to reopen if you have question related to Voyager + Kodein
