### ISSUE TITLE
Support tvos build targets

### ISSUE THREAD

**Issue by ScottPierce** [adrielcafe/voyager#218]
Supporting tvos should be a very simple add-on. Supporting tvos is the same as supporting ios in this use case.

All you would need to do is add the following kotlin multiplatform build targets:
```
tvosArm64()
tvosX64()
tvosSimulatorArm64()
```

**Comment by DevNatan** [comment]
@ScottPierce tvOS not supported by Compose Multiplatform :/

**Comment by ScottPierce** [comment]
I see that now :(
