### ISSUE TITLE
crash when app is going to background

### ISSUE THREAD

**Issue by savan-ixfi** [adrielcafe/voyager#219]
data class ExampleBottomSheet(
    val onSuccess: (String) -> Unit,
    val onDismiss: () -> Unit,
) : Screen {
    @Composable
    override fun Content() {
        ...
    }
}

How to handle lambda functions callback?

**Comment by osrl** [comment]
see https://github.com/adrielcafe/voyager/issues/39
you can't pass lambda to a screen.

**Comment by DevSrSouza** [comment]
You can try this result api sample instead of using lambdas.
https://github.com/adrielcafe/voyager/pull/128#issuecomment-1763034415
