### ISSUE TITLE
Preserve tab state in nested navigation

### ISSUE THREAD

**Issue by rafsanjani** [adrielcafe/voyager#229]
Given a tab navigation where each tab item has its own internal navigation, I would like the navigation state to be preserved in each tab. 

I have 3 tabs A-B-C

Where the tab A has internal navigation with screens A1 and A2. What I want is to save the navigation state of screen A so that navigating A->B->A will show the correct screen instead of resetting the navigation.

Screenshot
[Screen_recording_20231014_082643.webm](https://github.com/adrielcafe/voyager/assets/9197459/fd0c3407-5ba5-44f5-965a-cdb5b907adef)

**Comment by DevSrSouza** [comment]
Can you share a reproducible code?

**Comment by rafsanjani** [comment]
My bad I wasn't using unique screen keys closing!
