### ISSUE TITLE
BottomSheetNavigator constructor should be @InternalVoyagerApi

### ISSUE THREAD

**Issue by osrl** [adrielcafe/voyager#235]
BottomSheetNavigator's constructor is currently internal. This prevents us to provide a dummy navigator to previews. It's possible to do so to the Navigator like this;

```kotlin

@Composable
fun ComposeLocalWrapper(content: @Composable () -> Unit) {
    CompositionLocalProvider(
        LocalNavigator provides dummyNavigator,
        content = content
    )
}

@OptIn(InternalVoyagerApi::class)
val dummyNavigator
    @Composable get() = Navigator(
        listOf(DummyScreen),
        "Dummy",
        rememberSaveableStateHolder(),
        NavigatorDisposeBehavior()
    )
```

This way, we can use the ComposeLocalWrapper in Compose Previews. This is not possible for the BottomSheetNavigator, since it's constructor is internal

**Comment by osrl** [comment]
of course it's possible to use `@Suppress("INVISIBLE_MEMBER", "INVISIBLE_REFERENCE")` for workaround

**Comment by DevSrSouza** [comment]
It will be available at next release! Thanks for the contribution.
