### ISSUE TITLE
Not work coroutineScope in desktop module cmp

### ISSUE THREAD

**Issue by ITmind** [adrielcafe/voyager#239]
I'm writing an application in Compose Multiplatform (Kotlin Multiplatform) and using ScreenModel.
In common module:
```
class MainScreenModel(): ScreenModel {
    init{
        coroutineScope.launch {/* code */}
    }
}
```

When i run the application i get an error:
_Caused by: java.lang.IllegalStateException: Module with the Main dispatcher is missing. Add dependency providing the Main dispatcher, e.g. 'kotlinx-coroutines-android' and ensure it has the same version as 'kotlinx-coroutines-core'_

What needs to be done to make coroutines work?

I add dependencies "org.jetbrains.kotlinx:kotlinx-coroutines-core-jvm" but it did not help.

**Comment by DevNatan** [comment]
@ITmind [coroutines-swing is needed on Desktop platform](https://github.com/JetBrains/compose-multiplatform/releases/tag/v1.1.1)

**Comment by ITmind** [comment]
Thanks, it works
