### ISSUE TITLE
Desktop support on BottomSheetNavigator

### ISSUE THREAD

**Issue by pitampoudel** [adrielcafe/voyager#254]
I am not able to launch my compose multiplatform app on the desktop after I added BottomSheetNavigator composable function to my project.

I am getting an error that says:
```
This material API is experimental and is likely to change or to be removed in the future.

**Comment by Syer10** [comment]
https://kotlinlang.org/docs/opt-in-requirements.html

**Comment by pitampoudel** [comment]
@Syer10, That do not solves the problem. Please try it yourself once. Just use BottomSheetNavigator and try to launch on desktop.

**Comment by Syer10** [comment]
It works fine. You need to Opt-In to ExperimentalMaterialApi. The IDE should hint this already.
