### ISSUE TITLE
navigator.getNavigatorScreenModel method is creating singleton instance of ScreenModel

### ISSUE THREAD

**Issue by pitampoudel** [adrielcafe/voyager#258]
I have declared my screen model class on koin module as:
    factory<LoginScreenModel> {
        LoginScreenModel(get(), get(), get())
    }
    
 I am using navigator.getNavigatorScreenModel<LoginScreenModel>() method provided at package cafe.adriel.voyager.koin to get an instance of LoginScreenModel.
 
 It works fine but the problem is that the instance of LoginScreenModel is being persisted even after I go back and relaunched the screen (using the pop() method)

**Comment by Syer10** [comment]
That is the point of a [Navigator scoped ScreenModel](https://voyager.adriel.cafe/screenmodel#navigator-scoped-screenmodel), isn't it? You should be using [the regular getScreenModel function](https://voyager.adriel.cafe/screenmodel/koin-integration) if you don't want it persisted through the navigator

**Comment by pitampoudel** [comment]
Thank you! I will try
