### ISSUE TITLE
TabNavigator scoped ScreenModel

### ISSUE THREAD

**Issue by hypergonial** [adrielcafe/voyager#264]
Hello!

#233 added support for Navigator scoped ScreenModels, and I was wondering if it was possible (or if it even makes sense?) to add TabNavigator scoped ScreenModels as well. And if not, what workarounds would you advise?

Thanks!

**Comment by Syer10** [comment]
LocalNavigator inside a TabNavigator will point to the TabNaviagor's navigator. You can use that for scoped ScreenModels
