### ISSUE TITLE
screenModelScope crashing when used in desktop app

### ISSUE THREAD

**Issue by Kweku-A** [adrielcafe/voyager#272]
The default screenModelScope crashes when used in desktop app. I guess an instance of this is not provided on desktop platforms.

`Exception in thread "AWT-EventQueue-0" java.lang.NoSuchMethodError: 'android.os.Looper android.os.Handler.getLooper()'`

**Comment by Syer10** [comment]
See https://voyager.adriel.cafe/screenmodel/coroutines-integration#desktop-note

**Comment by Syer10** [comment]
Also, why or how are you trying to use the Android Looper on the desktop?

**Comment by Kweku-A** [comment]
> Also, why or how are you trying to use the Android Looper on the desktop?

I am not, that's the exception that was thrown.
Thanks for the reference
