### ISSUE TITLE
Wasm support

### ISSUE THREAD

**Issue by joreilly** [adrielcafe/voyager#274]
Are there plans to support Wasm target?

**Comment by Syer10** [comment]
Duplicate of #269 and #165

**Comment by joreilly** [comment]
Sorry, my bad (and just realise I added note to other issue here as well!).  Have been trying to see what libraries do/don't support it now and obviously got my own wires crossed on this one! And cool library btw!

**Comment by DevSrSouza** [comment]
https://github.com/adrielcafe/voyager/pull/289
