### ISSUE TITLE
BottomSheet voyager back handling error

### ISSUE THREAD

**Issue by Tolriq** [adrielcafe/voyager#28]
Currently the BackHandler is handled as 
```
    BackHandler(
        enabled = sheetState.isVisible,
```

This causes problems about the order of the backhandlers when others views have registered a BackHandler after the bottomsheet navigator as they will get the event first and will act on it before the BottomSheet.

The proper way is to add the back handler only when the sheet is visible, meaning it's always added last and will have the priority.

So 

```
if (sheetState.isVisible) {
     BackHandler(
```

**Comment by adrielcafe** [comment]
Perfect! Will be fixed in the next release o/
