### ISSUE TITLE
How to clear all previous screen

### ISSUE THREAD

**Issue by BlueSky15171** [adrielcafe/voyager#295]
My logic is:
splashScreen -> homeScreen -> press back -> android launcher
is actually：
splashScreen -> homeScreen -> press back -> splashScreen

android press return will return to splashScreen , what do I need to do, when starting homeScreen, there is only homeScreen in the stack

**Comment by Syer10** [comment]
`LocalNavigator.currentOrThrow.replaceAll(NewRootScreen())`
