### ISSUE TITLE
java.lang.IllegalArgumentException: Key PlayerScreen:transition was used multiple times 

### ISSUE THREAD

**Issue by BharatD94** [adrielcafe/voyager#306]
when relauch same screen 

navigator.push(PlayerScreen())

**Comment by Syer10** [comment]
If you have multiple of the same screens on the stack, it needs to be given a unique key like so https://voyager.adriel.cafe/state-restoration#identifying-screens

**Comment by BharatD94** [comment]
Thanks issue resolved
