### ISSUE TITLE
problem using rememberScreenModel

### ISSUE THREAD

**Issue by chingiz** [adrielcafe/voyager#308]
I'm trying to use `rememberScreenModel` in my `Screen` class

doing it like

```
object SignInScreen : Screen {
    override val key: ScreenKey = uniqueScreenKey

    @Composable
    override fun Content() {
        val screenModel = rememberScreenModel<SignInViewModel>()
        val navigator = LocalNavigator.currentOrThrow
        val state by screenModel.state.observeAsState()
       }
}
```
but this line gives an error saying
`val screenModel = rememberScreenModel<SignInViewModel>()` **no value passed for parameter factory**

Note: I'm using koin and my viewModel is `LiveScreenModel`

**Comment by mainrs** [comment]
You have to tell voyager how to create an instance of your `ScreenModel`. `rememberScreenModel` takes a lambda. If you want to get the Koin instance screen model, you have to do it according to the documentation:

https://voyager.adriel.cafe/screenmodel/koin-integration

**Comment by DevSrSouza** [comment]
@chingiz the [Koin extension](https://voyager.adriel.cafe/screenmodel/koin-integration) follows the Koin naming convention.

So in this case is `getScreenModel<Type>()`
