### ISSUE TITLE
BottomSheetNavigator does not properly handle click outside to dismiss

### ISSUE THREAD

**Issue by Tolriq** [adrielcafe/voyager#32]
When clicking outside the bottomsheet to close it, the navigator is not involved currently, meaning that it won't replace the stack leading to display issue on the next show + keeping the composables / viewmodel in memory.

Solution is to use the confirmStateChange parameter of the sheet state and when the target is Hidden, manually call the navigator hide and return false to not let the default handling happen.

**Comment by adrielcafe** [comment]
Thanks again! Will be fixed in the next release.
