### ISSUE TITLE
Could I nest a TabNavigator in another TabNavigator?

### ISSUE THREAD

**Issue by walfud** [adrielcafe/voyager#335]

**Comment by walfud** [comment]
> Yes

But when I nest tabnavigator(as A) in another(as B), I try to get `LocalTabNavigator.current` will get outer instance. I'll put demo code tomorrow.

**Comment by Syer10** [comment]
I get what you are saying, but it doesn't matter. Just create a new composition local for the parent one.

**Comment by walfud** [comment]
> I get what you are saying, but it doesn't matter. Just create a new composition local for the parent one.

Yes, as you say. TabNavigator can nest with any other navigator. 
I'll close thread.

thank you
