### ISSUE TITLE
Crash due to Parcelable encountered IOException writing serializable

### ISSUE THREAD

**Issue by YoussefHachicha** [adrielcafe/voyager#340]
![Screenshot 2024-02-21 at 8 26 32 AM](https://github.com/adrielcafe/voyager/assets/126149415/fa36fbb5-3f84-460b-895b-5140bca6ded4)
when i pass to my Screen this
if i leave the app in the backGround it will crash with this message:
Parcelable encountered IOException writing serializable object (name = quran.navigation.quran.QuranScreenNav)

**Comment by enoler** [comment]
Same problem here, it happens if for example I open via Intent a link i a browser.

**Comment by shpasha** [comment]
Suppose, that ScreenSize is not serializable model. Try to obtain it through composition local providers

**Comment by DevSrSouza** [comment]
Voyager Screens parameters should act like a State that can the Save with the `Saver` Compose API.

By default all Voyager Screen are `Java Serializable`, but you can override it by using for exemple `Parcelable` if you want.

**Comment by N-Pu** [comment]
I have the same problem  and don't really understand how to solve it.

**Comment by N-Pu** [comment]
> Voyager Screens parameters should act like a State that can the Save with the `Saver` Compose API.
> 
> By default all Voyager Screen are `Java Serializable`, but you can override it by using for exemple `Parcelable` if you want.
> 
> @shpasha recommendation is the best for solving your issue

Sorry, could you have a code example for this one? That would be very helpful.

**Comment by YoussefHachicha** [comment]
I have the same problem and don't really understand how to solve it.

just dont pass a non serilazeable object 
my issue was that i was passing this 
object HomeChatTab(val navigator: Navigator)

**Comment by YoussefHachicha** [comment]
I solved the problem, its due to passing a Navigator Instance from a Screen to. a Screen instead i used the
val navigator = LocalNavigator.currentOrThrow.parent
