### ISSUE TITLE
iOS build error

### ISSUE THREAD

**Issue by joreilly** [adrielcafe/voyager#342]
Getting following error building iOS client (using version `1.1.0-alpha03` in shared KMP code)....all other clients build ok.

```
> Task :composeApp:kspKotlinIosSimulatorArm64 FAILED
e: Could not find "androidx.annotation:annotation" in [/Users/joreilly/dev/github/ClimateTraceKMP, /Users/joreilly/.konan/klib, /Users/joreilly/.konan/kotlin-native-prebuilt-macos-aarch64-2.0.0-Beta2/klib/common, /Users/joreilly/.konan/kotlin-native-prebuilt-macos-aarch64-2.0.0-Beta2/klib/platform/ios_simulator_arm64]
```

**Comment by joreilly** [comment]
Seeing issue in this branch fwiw https://github.com/joreilly/ClimateTraceKMP/tree/voyager

**Comment by Syer10** [comment]
You need to add the google() repository as listed in the Compose changelogs https://github.com/JetBrains/compose-multiplatform/releases/tag/v1.6.0-rc01

**Comment by joreilly** [comment]
I do have that repository included....do see following so maybe an issue...

```
org.jetbrains.compose.runtime:runtime:1.6.0-beta01 -> 1.6.0-rc03
```

**Comment by joreilly** [comment]
Just to confirm that it was tha tissue.....merged now to https://github.com/joreilly/ClimateTraceKMP
