### ISSUE TITLE
Voyager hilt support broken with Dagger 2.51

### ISSUE THREAD

**Issue by Tolriq** [adrielcafe/voyager#346]
Dagger 2.51 (https://github.com/google/dagger/releases/tag/dagger-2.51) have breaking change impacting Voyager.

This is probably caused by https://github.com/google/dagger/commit/408431a3bb4db983f27bb96122167ca4cf41322e and the constructor of `InternalViewModelFactory` being internal.

**Comment by nvkleban** [comment]
I made a small PR with fix, waiting for approval.
