### ISSUE TITLE
Recommended way to implement application that requires login?

### ISSUE THREAD

**Issue by tethridge** [adrielcafe/voyager#370]
The documentation doesn't show the best practice for using voyager with a login screen.  

I'm hoping that there is a way to collect from a flow that has states unauthenticated, loading, and authenticated.  When unauthenticated, the login page is shown.  After the user enters their credentials and submits them the loading screen is shown. If the credentials are valid, then the main screen is shown.  Otherwise, the user is returned to the login screen.

I'm having difficulty getting it to work properly with transitions.  Can somebody provide an example?

**Comment by maxoertel** [comment]
Hey @tethridge , I'm trying the same right now. This is my approach, but even thoughh `currentContent2` changes, the navigator does not redraw.

```
class MainScreen : Screen {

    override val key: ScreenKey = uniqueScreenKey

    @Composable
    override fun Content() {
        val screenModel = getScreenModel<MainScreenModel>()
        val userRepository = koinInject<UserRepository>()

        var currentContent by remember { mutableStateOf<Screen>(SplashScreen()) }

        LaunchedEffect(true) {
            userRepository.isLoggedIn.collect { value ->
                when (value) {
                    true -> {
                        currentContent = HomeScreen().also { println("set to Home") }
                    }
                    false -> {
                        currentContent = LoginScreen().also { println("set to Login") }
                    }
                }
            }
        }

        Navigator(currentContent)
    }
}
```

Maybe we find a solution together?

**Comment by tethridge** [comment]
// This sort of works, but I'd like to have transitions.
        @Composable
        fun App() {
            MyAppTheme {
                Navigator(MainScreen()) { navigator ->
                    val rootScreenModel = navigator.getNavigatorScreenModel<RootScreenModel>()
                    val state by rootScreenModel.state.collectAsState()
        
                    when (state) {
                        is RootScreenModel.State.Authenticated -> {
                            println("Authenticated")
                        }
        
                        is RootScreenModel.State.Unauthenticated -> {
                            println("Unauthenticated: pushing login screen")
                            navigator.push(StartLoginScreen())
                        }
                    }
        
                    CurrentScreen()
        
                    // Adding transitions causes issues with reloading of content
                    //SlideTransition(navigator)
                }
            }
        }

**Comment by maxoertel** [comment]
I understand. Works for me too without transitions. I'll try around with transitions and let you know if I find sth!

**Comment by DevSrSouza** [comment]
I would encourage to go on [Discussions](https://github.com/adrielcafe/voyager/discussions), issues are more focus on bugs and feature request.
