### ISSUE TITLE
Update compose version to 1.6.1

### ISSUE THREAD

**Issue by Cuyer** [adrielcafe/voyager#373]
I have issue building IOS project, most propably because Voyager library uses compose 1.6.0-beta01 which is incompatibile with higher versions of compose. The highest versions of compose that work with Voyager is 1.6.0-beta02.

This issue is explained here:
https://github.com/JetBrains/compose-multiplatform/issues/4277#issuecomment-1945922199

Also I've created issue in compose multiplatform Github that explains my issue more:
https://github.com/JetBrains/compose-multiplatform/issues/4525

**Comment by DevSrSouza** [comment]
We have merge a update of the compose to Stable 1.6.0, it should fix this issue as well!
