### ISSUE TITLE
Cant pass a lambda to a Screen

### ISSUE THREAD

**Issue by YoussefHachicha** [adrielcafe/voyager#374]
when ever i pass a non serilizable object to a screen if i leave the app in the background and open it again it will crash 
for example i passed this lambda here 
class HomeNav(
    private val onThemeChange: (QuranTheme) -> Unit,
) : Screen {

any idea on how can i be able to change the theme without passing a lambda ?

**Comment by DevSrSouza** [comment]
Voyager screens act as State, all screen should be able to be restored, lambdas are no allowed.
https://voyager.adriel.cafe/state-restoration

I will close this issue as not planned.
Design decisions on how to find a way to do `onThemeChange` you will need to go deeper in details and I suggest go to [Discussions](https://github.com/adrielcafe/voyager/discussions)

**Comment by YoussefHachicha** [comment]
thanks but do you have any idea on how can i pass that?
