### ISSUE TITLE
Using Voyager-Koin with wasm in Kotlin Multiplatform

### ISSUE THREAD

**Issue by landmuc** [adrielcafe/voyager#392]
I'm trying to add the voyager-koin dependency to my km-project targeting android, ios and web using this version "cafe.adriel.voyager:voyager-koin:1.1.0-alpha04". Version 1.1.0-alpha03 of voyager states the wasm support was added ("WASM support by @DevSrSouza in https://github.com/adrielcafe/voyager/pull/289"). Since I am using other voyager dependencies like voyager-navigator and voyager-screenmodel I am wondering if there is yet not support for voyager-koin or if I am doing something wrong?
Has anyone successfully implemented voyager-koin in a km-project with wasm?

**Comment by DevSrSouza** [comment]
Currently, the `voyager-koin` module is using stable version for Koin Compose, this version does not have support to wasm yet.
If you want to use Voyager Koin extensions, you can just copy the functions and use in your project and it should work out of the box with Koin Compose Wasm.
