### ISSUE TITLE
remember loses state after navigation

### ISSUE THREAD

**Issue by Faltenreich** [adrielcafe/voyager#405]
I am experiencing state loss in the following example:

```
data object A : Screen {

    @Composable
    override fun Content() {
        val cached = remember { mutableStateOf(0f) }
        Button(onClick = { cached.value = cached.value + 1 }) {
            Text(cached.value.toString())
        }
    }
}
```

If I leave `A` to another `Screen` and then navigate back (via back press) to `A`, `cached` is reset to its initial state of `0f`.

Is this intended behavior and I would have to use `rememberSaveable` instead of `remember`, or am I doing something wrong?

I am using version `1.1.0-alpha04` of Voyager in a multiplatform environment.

Thanks in advance, have the nicest of days and thank you so much for this awesome library!

Kind regards

**Comment by thennothinghappened** [comment]
This actually brings me to something that had me lost on Voyager myself, in the _reverse_ scenario where you have some data that's coming down from the top (that's mutable), or some class instance to need to pass to a ScreenModel to be used, all the documentation suggests is "use a DI framework" which isn't really a helpful answer IMO.

Since `Content` takes no arguments that knocks out the most obvious method, and any arguments on a `Screen` must be saveable to disk, which isn't what you want for taking in a shared service or something like that. I ended up thinking back to just using composition locals as the easiest solution, but it makes me feel like I'm missing something obvious - same feeling I've got from a lot of Voyager, and I'd really like someone to point out to me what exactly it is so I can get on with using it, because it seems so close to being so nice!

**Comment by Syer10** [comment]
A DI Framework is basically a Composition Local overcharged, so you are on the right path by thinking CompositionLocal

**Comment by thennothinghappened** [comment]
> A DI Framework is basically a Composition Local overcharged, so you are on the right path by thinking CompositionLocal

Huh, alright then!
Would something like this be on the right track, or something different?

```kt
val LocalSomeRepo: ProvidableCompositionLocal<ISomeRepo> = staticCompositionLocalOf {
    error("No repository provided!")
}

class SomeScreenModel(
    private val someRepo: ISomeRepo
) : ScreenModel {

    private val mutableState: MutableStateFlow<State> = MutableStateFlow(State.None)
    val state = mutableState.asStateFlow()

    fun doThing() {
        
        mutableState.update { State.Loading }

        screenModelScope.launch {
            withContext(Dispatchers.IO) {
                mutableState.update {
                    when (val response = someRepo.getThing()) {
                        is Response.Failure -> State.Failed(response.error)
                        is Response.Success -> State.Success(response.data)
                    }
                }
            }
        }

    }

    sealed interface State {
        data object None : State
        data object Loading : State
        data class Failed(val error: Throwable) : State
        data class Success(val data: SomeData) : State
    }

}

class SomeScreen : Screen {

    @Composable
    fun Content() {
        
        val screenModel = rememberScreenModel { SomeScreenModel(LocalSomeRepo.current) }
        val state = screenModel.state.collectAsState().value

        Column {
            when (state) {

                is SomeScreenModel.State.Loading -> {
                    CircularProgressIndicator()
                }

                is SomeScreenModel.State.Failed -> {
                    Text("Failed to load: ${state.error}")
                    GoButton(screenModel::doThing)
                }

                is SomeScreenModel.State.None -> {
                    GoButton(screenModel::doThing)
                }

                is SomeScreenModel.State.Success -> {
                    Text(state.data.toString())
                }

            }
        }

    }

    @Composable
    fun GoButton(doThing: () -> Unit) {
        Button(onClick = doThing) {
            Text("Load some data")
        }
    }
}

@Composable
fun App() {
    Navigator(SomeScreen()) {
        CurrentScreen()
    }
}
```

### Implementations for passing some platform-specific initialized service

#### Android

```kt
class SomeActivity : ComponentActivity() {

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)

        val somePlatformSpecificRequirement = /* ... */
        val someRepo: ISomeRepo = SomeRepoBuilder(somePlatformSpecificRequirement).build()

        setContent {
            CompositionLocalProvider(LocalSomeRepo provides someRepo) {
                App()
            }
        }
    }

}
```

#### Desktop

```kt
fun main() {

    val somePlatformSpecificRequirement = /* ... */
    val someRepo: ISomeRepo = SomeRepoBuilder(somePlatformSpecificRequirement).build()

    application {
        Window(
            resizable = true,
            onCloseRequest = ::exitApplication
        ) {
            CompositionLocalProvider(LocalSomeRepo provides someRepo) {
                App()
            }
        }
    }

}
```

**Comment by Syer10** [comment]
Yep, that would work. I do the same in some projects/

**Comment by thennothinghappened** [comment]
> Yep, that would work. I do the same in some projects.

Good to know, thanks!
Though, as for "some" projects - would there be an alternative you'd usually go with?

**Comment by Syer10** [comment]
DI Frameworks like Kotlin-Inject. Koin is also easy to use. I use Kotlin-Inject here if you want to take a look at how I use it https://github.com/Suwayomi/Suwayomi-JUI

**Comment by Faltenreich** [comment]
Thank you very much for your responses! This confirms what I assumed but was not entirely sure about before.
I will close this issue as my question has been anwered, but feel free to continue the discussion as you please.
