### ISSUE TITLE
voyager-koin causes build error for iOS Simulator

### ISSUE THREAD

**Issue by janesp** [adrielcafe/voyager#413]
Voyager `Navigation` tutorial (https://youtu.be/7Xv38k4cCMc) works fine for Android and iOS (can be cloned under https://github.com/janesp/VoyagerBase, see also for versions).

Voyager `ScreenModel` tutorial (https://youtu.be/L39NrirKohg) causes build error for iOS Simulator.

Easiest way to reproduce:

- Clone https://github.com/janesp/VoyagerBase and build for Android and iOS
- Incrementally add dependencies as per `ScreenModel` tutorial and build for every step
- As soon as `voyager-koin` dependency is added, iOS build error occurs

Environment:

- MacBook Pro 2021, M1 Max
- macOS Sonoma 14.4.1
- Android Studio Jellyfish
- xcode 15.3

**Comment by DevSrSouza** [comment]
Try to update to [1.1.0-alpha04](https://github.com/adrielcafe/voyager/releases/tag/1.1.0-alpha04)

**Comment by janesp** [comment]
> Try to update to [1.1.0-alpha04](https://github.com/adrielcafe/voyager/releases/tag/1.1.0-alpha04)

Cool - this fixed the issue 😊, many thanks!
