### ISSUE TITLE
Dispatchers.Main in androidUnitTest kmm

### ISSUE THREAD

**Issue by droideveloper** [adrielcafe/voyager#419]
is there a way to make `PlatformMainDispatcher` actual for android instead of `Dispatcher.Main.immediate` to `Dispatchers.Main`
would not let me mockk Dispachers.Main 🤔

**Comment by DevSrSouza** [comment]
`Dispatchers.setMain` does not work for the case?

**Comment by droideveloper** [comment]
well actually on each before I did set `Dispatchers.setMain(UnconfinedTestDispatcher())` 
I do have dependencies in `build.gradle.kt`
```kotlin
        androidUnitTest.dependencies {
            implementation(libs.coroutines.core)
            implementation(libs.coroutines.android)
            implementation(libs.coroutines.test)
            implementation(libs.mockk)
        }
```
but when run tests it fails with `HandlerDispatcher` etc error, so I was wondering `immediate` usage of it could be reason for it ? thanks.

**Comment by droideveloper** [comment]
and if I use it like this in `@Before`
```kotlin
mockkStatic("cafe.adriel.voyager.core.model.ScreenModelKt")
 every { screenModel.screenModelScope } returns testScope
 ```
 and `testScope` is
 ```kotlin
 private val testScope = TestScope(UnconfinedTestDispatcher())
 ```
 I could run my tests

**Comment by droideveloper** [comment]
We went with option to provider func 
```kotlin
class FooScreenModel(
    private val scope: ScreenModel.() -> CoroutineScope = { screenModelScope },
)```

and provide `TestScope` in our tests, for anyone has same issue
