### ISSUE TITLE
AndroidScreen() ViewModel retained after activity is finished

### ISSUE THREAD

**Issue by aurimas-zarskis** [adrielcafe/voyager#47]
I have an issue of AndroidScreens ViewModel being retained when activity is finished. This seems to only happen to root navigator screen. So when I am in my root view and press back, activity finishes, when I open the app again, screen gets the same ViewModel that has some state retained. Using regular Screen doesn't have this issue

**Comment by adrielcafe** [comment]
Thanks for reporting. #24 is about the same issue, closing due to duplication.
