### ISSUE TITLE
Unable to declare screens on commonMain

### ISSUE THREAD

**Issue by xxfast** [adrielcafe/voyager#48]
I'm running into a weird issue with this library, that I haven't yet run into with other multiplatform libraries 

I have a multiplatform module that targets android and desktop, which is setup like 
```kotlin
import org.jetbrains.compose.compose

plugins {
  id("com.android.library")
  kotlin("multiplatform")
  id("org.jetbrains.compose")
}

kotlin {
  android { .. }

  jvm("desktop") { .. }

  sourceSets {
    val commonMain by getting {
      dependencies {
        implementation(compose.runtime)
        ..
        implementation(Adriel.voyagerNavigator)
        implementation(Adriel.voyagerTabNavigator)
      }
    }

    val androidMain by getting { .. }
    val desktopMain by getting { .. }
  }
}
```
However, when I try to declare any screens in the `commonMain`, I get
<img width="958" alt="Screen Shot 2022-02-21 at 4 18 16 pm" src="https://user-images.githubusercontent.com/13775137/154893857-708960a7-e9e9-451e-8abe-019d7207fb4f.png">

If I move to the declaration to `desktopMain`, it works just fine. Any idea why is this happening 🤔

**Comment by DevSrSouza** [comment]
I test here and seems to be building even with AS/IntelliJ yelling. 

I did a quick fix by changing in the gradle.properties: `kotlin.mpp.enableGranularSourceSetsMetadata=false` 

I'm still trying to understand why this is not working with `true`, this also happening with my [`compose-icons`](https://github.com/DevSrSouza/compose-icons) library

**Comment by adrielcafe** [comment]
Closing since it's not a library issue.

Feel free to reopen if find a better solution/workaround.
