### ISSUE TITLE
Support state restoration?

### ISSUE THREAD

**Issue by andkulikov** [adrielcafe/voyager#5]
Hello and thanks for the library.

I am an engineer from Compose team at Google and wanted to mention that there is an expectation from the navigation library in Compose that this will save the inner state of the components which are currently in the backstack. Examples are the scrolling position of the LazyColumn should be restored when you go from screen with the list to the second screen and then go back to the list screen.
Other navigation libraries like the official one from androidx of [Decompose](https://github.com/arkivanov/Decompose) support it as they use the special API designed to make is simpler: https://developer.android.com/reference/kotlin/androidx/compose/runtime/saveable/SaveableStateHolder
Please let me know if you will have any questions, thanks!

**Comment by adrielcafe** [comment]
There's an discussion (#4) about that, started by @Grouen. 

I'm doing some experiments with `SaveableStateRegistry` but seems that `SaveableStateHolder` avoids a lot of boilerplaite. I'll start using it from now on.

Thanks for the tip! Hope to have something working soon.

**Comment by adrielcafe** [comment]
Just released [1.0.0-beta03](https://github.com/adrielcafe/voyager/releases/tag/1.0.0-beta03) with this improvement. If you find any weird behavior, please let me know.

Thanks again @andkulikov !
