### ISSUE TITLE
Compose Multiplatform Transitions Don't Work

### ISSUE THREAD

**Issue by Janglinator** [adrielcafe/voyager#509]
When running the multiplatform sample of this repo (`main` branch), there are no transitions.  I tried adding one according to the [docs](https://voyager.adriel.cafe/transitions-api/), but still no luck.

Running the Android sample project works great.

I also have a personal multipatform project running beta03 where transitions aren't working either.

Is this expected behavior?

It might be worth adding a note to the docs if this is the case.

**Comment by Syer10** [comment]
It is not, did you make sure to add the transition to all navigators in your project? Each platform might have its own navigator you need to modify.

**Comment by Janglinator** [comment]
Interesting.  I tried to apply them to the sample but had no luck.  I'll give it another try, at the very least it could result in a useful PR

**Comment by Janglinator** [comment]
Not sure what I did wrong in the first attempt at the sample, but worked this time.  I tossed up a quick PR, going to go figure out what I did wrong in my project.  Thanks!
