### ISSUE TITLE
Can't use kodein rememberScreenModel in the common module

### ISSUE THREAD

**Issue by dragossusi** [adrielcafe/voyager#56]
Hello, I am trying ot use `cafe.adriel.voyager.kodein.rememberScreenModel` to create my screen model but it is not available in `commonMain`.

**Comment by adrielcafe** [comment]
Hi! How are you importing it in `build.gradle`?

**Comment by adrielcafe** [comment]
This can be related with #48. Please, also try the suggested workaround by @DevSrSouza . It's not a library issue.

**Comment by dragossusi** [comment]
@adrielcafe it has nothing to do with that issue.
If you go to `voyager-kodein/src/` you will see that there is no `commonMain` folder, the method is implemented twice for both android and JVM, don't know why as everything needed in those methods is available in common as well.

**Comment by dragossusi** [comment]
My workaround was to copy paste the implementation myself in my project and place it in `commonMain`

**Comment by adrielcafe** [comment]
Ah, perfect! Just fixed in [1.0.0-rc01](https://github.com/adrielcafe/voyager/releases), thanks for your help o/
