### ISSUE TITLE
1.0 RC01 side effect on tab navigation

### ISSUE THREAD

**Issue by Tolriq** [adrielcafe/voyager#58]
The fix (https://github.com/adrielcafe/voyager/pull/55) have the side effect of now fully unloading the view models when navigating between tabs.

While the fix is normal and wanted, due to the current limitations of LazyList not proposing any proper way to delay the state restoration,  this makes restoring scroll position insanely complex until they propose something.

It would be nice to have a way to opt out or a workaround for this use case.

**Comment by Tolriq** [comment]
So seems all that is missing is a function on SnapshotStateStack to be able to reorder / modify the stack.

could be a moveToFrontOrPush(item) or just a remove(item) that return the item or null that we can then push. The difficulty is to decide about the events to emit.

**Comment by adrielcafe** [comment]
I've added a `disposeNestedNavigators` param on `TabNavigator` in [1.0.0-rc02](https://github.com/adrielcafe/voyager/releases/tag/1.0.0-rc02), that way you can control the disposal behavior of nested navigators inside tabs.

Please let me know if this solves your issue.

**Comment by Tolriq** [comment]
Thanks, this works for the need.

This is still a little to global option to address https://github.com/adrielcafe/voyager/issues/25 but that's another story that can be workaround.

**Comment by adrielcafe** [comment]
Indeed, I'll work on a more granular approach for #25 .

**Comment by Tolriq** [comment]
I have a custom tabnavigator and workaround the need, so not sure it's worth changing the API surface that late in the process.

So don't block an 1.0 release for that, it's not worth it as quite specific need.
