### ISSUE TITLE
screen model doesn't survive the configuration changes

### ISSUE THREAD

**Issue by Anton111111** [adrielcafe/voyager#62]
I try use Screen + ScreenModel + Hilt.

I create Screen like this:
```
object SearchScreen : Screen {

    @Composable
    override fun Content() {
        val screenModel = getScreenModel<SearchScreenModel>()
        Log.e("!!!!","!!!!Use screenmodel: $screenModel")
        SearchScreen(screenModel)
    }
}
```

And my ScreenModel:
```
class SearchScreenModel @Inject constructor(
    private val searchUseCase: SearchUseCase
) : ScreenModel {
   //Some code
}
```

But  when i rotate my phone screen model recreated. Shouldn't the screen model survive the configuration changes? OR am I doing something wrong?

**Comment by Anton111111** [comment]
I think Hilt has nothing to do with it. I tried to do it without Hilt and still the ScreenModel is recreated. Maybe I'm not understanding correctly and it should be recreated when the phone rotates?

**Comment by Anton111111** [comment]
I'm completely bewildered right now. I run the sample application and it works as it should. I completely copy the Activity, Screen, ScreenModel code in my app (where I want to migrate to voyager) and the screenmodel starts recreating when I flip the phone. Can anyone help me ?

**Comment by Syer10** [comment]
Try this, `object SearchScreen : Screen` should be `class SearchScreen : AndroidScreen` and you should use remember { SearchScreen() } if this is your initial screen in the navigator. I cant tell anything else without looking at your code

**Comment by Anton111111** [comment]
> Try this, `object SearchScreen : Screen` should be `class SearchScreen : AndroidScreen()` and you should use remember { SearchScreen() } if this is your initial screen in the navigator. I cant tell anything else without looking at your code.

Where i need to use ```remember { SearchScreen() }``` ?
I look at sample:
https://github.com/adrielcafe/voyager/blob/main/samples/android/src/main/java/cafe/adriel/voyager/sample/hiltIntegration/HiltMainActivity.kt

It started with  Navigator(HiltListScreen())

**Comment by Syer10** [comment]
Something like `Navigator(remember { HiltListScreen() })`

Its a safeguard because Compose can re-create classes based on parent composables.

**Comment by Anton111111** [comment]
> Something like `Navigator(remember { HiltListScreen() })`

Here is cleaned project to show my problem:
https://github.com/Anton111111/VoyagerPlayground

Here is Activity:
https://github.com/Anton111111/VoyagerPlayground/blob/main/mobile/src/main/java/com/anton111111/anorak/ui/app/AppActivity.kt

Here is Screen:
https://github.com/Anton111111/VoyagerPlayground/blob/main/feature/movies/ui/src/main/java/com/anton111111/anorak/movies/ui/search/HiltListScreen.kt

When i rotate phone i see that screen is not recreated. But screen model is recreated.

**Comment by Anton111111** [comment]
> Something like `Navigator(remember { HiltListScreen() })`

I tried with remember. Same result ;(

**Comment by Syer10** [comment]
Ok I did some testing and this bug seems to be related to the changes done in 1.0.0-rc01, it doesnt happen in 1.0.0-beta16. SO I guess use 1.0.0-beta16 for now until its fixed

**Comment by Anton111111** [comment]
> So I guess use 1.0.0-beta16 for now until its fixed

You are right! Thanks! On 1.0.0-beta16 it works good.

My problem is i started sample app from main branch where issue solved already.

**Comment by adrielcafe** [comment]
I've commented on #66 about a refactoring I'm doing that should solve all Android related issues (including configuration changes). It may take a while but will be worth it.

**Comment by beyondeye** [comment]
@Anton111111 
Hi , I have just published a fork of voyager with **bug fixes** and **new features** [here](https://github.com/beyondeye/compose_bloc).
I will be happy to have your feedback. 
This specific issue has been solved in my fork.
