### ISSUE TITLE
Replace Tab's `options` to `getOptions(key: Any? = null)`

### ISSUE THREAD

**Issue by Dr-TSNG** [adrielcafe/voyager#64]
Sometimes we need to display different icons or titles according to different situations, such as whether the tab is selected or not, so it is good to provide such interface.

**Comment by adrielcafe** [comment]
What is this `key`? The screen key or a custom key to be used on `remember`?

The ` options` has a `@Composable get`, so you can get the `TabNavigator` and check if it is selected:
```
val options: TabOptions
  @Composable
  get {
    val tabNavigator = LocalTabNavigator.current
    return if (tabNavigator.current.key == key) {
      ...
    } else {
      ...
    }
  }
```
