### ISSUE TITLE
How to multiple instance viewmodel for same compose fun

### ISSUE THREAD

**Issue by zakrodionov** [adrielcafe/voyager#7]
I have a list of items and a detail screen. Detail Screen is a compose function that takes a (post) parameter that I pass as an argument to the ViewModel. 
`        val viewModel = getStateViewModel<PostDetailViewModel>(parameters = { parametersOf(args) })
`
The problem is that it looks like the viewModel is cached, and all the time it opens the first post (argument) that was followed.

In jetpack navigation works correctly.

https://user-images.githubusercontent.com/27068529/129693071-ade8b0bc-1c0e-4bc0-a367-cceac22c4e53.mp4

**Comment by davidbilik** [comment]
I've just encountered exactly the same issue. Maybe it's a problem with Koin?

**Comment by adrielcafe** [comment]
Are you guys using `SavedStateHandle` in the ViewModel? If not, it works with `by viewModel()`?

**Comment by davidbilik** [comment]
Nope, this is my code that is called from the `Content` function of my `Screen`
```
@Composable
fun SessionDetailScreen(
    archiveItem: UiArchiveItem,
    subsessionItem: UiSubSession?,
    vm: SessionDetailViewModel = getViewModel(parameters = {
        parametersOf(archiveItem, subsessionItem)
    })
) {
...
```
and I am using Koin for retrieving VM https://insert-koin.io/docs/reference/koin-android/compose/#viewmodel-for-composable

**Comment by adrielcafe** [comment]
Since we are in the same activity the `ViewModelStoreOwner` is the same between screens (https://github.com/InsertKoinIO/koin/issues/1142). Internally it uses a `Map<String, ViewModel>`  and Koin uses the qualifier as the key. Because of that we get the same ViewModel even if the params are different.

The solution for that is to implement `ViewModelStoreOwner` in our screens:
```kotlin
class DetailsScreen(
    val id: Int
) : Screen, ViewModelStoreOwner {

    private val viewModelStore = ViewModelStore()

    override fun getViewModelStore() = viewModelStore

    @Composable
    override fun Content() {
        CompositionLocalProvider(
            LocalViewModelStoreOwner provides this
        ) {
            val viewModel = getViewModel<DetailsViewModel> { parametersOf(id) }

        }
    }
}
```

I'm looking for a way to integrate that on Voyager, in the meamtime you can use the above snippet as workaround.

**Comment by davidbilik** [comment]
But when I used navigation-compose from Jetpack this problem was not there. I've refactored my app to Voyager because of arguments passing and then it started. Koin should have this solved IMO, it wouldn't make sense if there would be such limitation

**Comment by adrielcafe** [comment]
It works on navigation-compose because [NavBackStackEntry implements ViewModelStoreOwner](https://cs.android.com/androidx/platform/frameworks/support/+/androidx-main:navigation/navigation-common/src/main/java/androidx/navigation/NavBackStackEntry.kt;l=68?q=androidx.navigation.NavBackStackEntry&ss=androidx%2Fplatform%2Fframeworks%2Fsupport), so I have to do the same. 

Working on that, shouldn't take long.

**Comment by adrielcafe** [comment]
Just released [1.0.0-beta06](https://github.com/adrielcafe/voyager/releases/tag/1.0.0-beta06) with a new module: `voyager-androidx`. Just replace `Screen` with `AndroidScreen`  and ViewModels should now work as expected ([docs](https://voyager.adriel.cafe/navigation/androidx-and-viewmodel)).

Closing the issue, but feel free to re-open if needed.

**Comment by davidbilik** [comment]
Works like a charm! Thanks :)

**Comment by zakrodionov** [comment]
@adrielcafe Thanks for your quick help! It worked for me only without SavedStateHandle, is there a way to use it with SavedStateHandle?

**Comment by adrielcafe** [comment]
@zakrodionov the ViewModel still is the same when you use the SavedStateHandle, or the SavedStateHandle content is not being saved? Can you provide a code snippet please?

**Comment by zakrodionov** [comment]
@adrielcafe If I use getViewModel everything is ok. But with getStateViewModel an in-memory reference to the same viewModel. It looks like the problem is in the SavedStateRegistryOwner.
![pic1](https://user-images.githubusercontent.com/27068529/130788034-0b5405b6-5f8f-4bbf-9762-3e40474dc470.png)

**Comment by zakrodionov** [comment]
@adrielcafe Yes, it works. Thank you so much!

**Comment by Faltenreich** [comment]
I am experiencing the same problem on multiplatform, but there is no AndroidScreen available, even when including `cafe.adriel.voyager:voyager-androidx`. Is there another way to push the same Screen twice and if so, with changed parameters as well?
