### ISSUE TITLE
When I use hilt with version 2.44, getViewModel cannot get instance my ViewModel.

### ISSUE THREAD

**Issue by TNEllsworth** [adrielcafe/voyager#94]
When I use hilt with version 2.44, getViewModel cannot get instance my ViewModel.

java.lang.IllegalArgumentException: CreationExtras must have a value by SAVED_STATE_REGISTRY_OWNER_KEY

I updated version to 2.42, then all this was OK.

_Originally posted by @TNEllsworth in https://github.com/adrielcafe/voyager/discussions/93_

**Comment by Syer10** [comment]
The fix for this is included in one of my PRs https://github.com/adrielcafe/voyager/pull/88
It is also included in my fork of Voyager here: https://github.com/Syer10/voyager
