### ISSUE TITLE
iOS / Full Multiplatform Support?

### ISSUE THREAD

**Issue by ScottPierce** [adrielcafe/voyager#98]
Getting official support for ios, and the other kotlin multiplatform targets would be great. It seems like people are [forking the library](https://github.com/Syer10/voyager) to add this. It'd be great if the main project just did it.

**Comment by jershell** [comment]
Any news?

**Comment by terrakok** [comment]
@DevSrSouza Any updates here? the fork mentioned above works fine ☝️

**Comment by DevSrSouza** [comment]
I will talk with the fork owner and bring the code to here
